# Generated by Django 2.2.13 on 2020-08-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app and see timers"),
                    ("create_timer", "Can create new timers and edit own timers"),
                    ("manage_timer", "Can edit and delete any timer"),
                    ("opsec_access", "Can create and see opsec timers"),
                ),
            },
        ),
        migrations.AlterModelOptions(name="timer", options={},),
    ]
