# Generated by Django 2.2.13 on 2020-08-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="notificationrule", name="minutes",),
        migrations.AddField(
            model_name="notificationrule",
            name="time",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (None, "---------"),
                    (0, "T - 0 minutes"),
                    (5, "T - 5 minutes"),
                    (10, "T - 10 minutes"),
                    (15, "T - 15 minutes"),
                    (30, "T - 30 minutes"),
                    (45, "T - 45 minutes"),
                    (60, "T - 60 minutes"),
                    (90, "T - 90 minutes"),
                    (120, "T - 120 minutes"),
                ],
                db_index=True,
                default=None,
                help_text="When to sent a notification in relation to when the timer elapses. Use together with `elapses soon` trigger.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notificationrule",
            name="trigger",
            field=models.CharField(
                choices=[("TC", "Timer created"), ("TE", "Timer elapses soon")],
                default="TE",
                help_text="Trigger for sending a notification",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="ping_type",
            field=models.CharField(
                choices=[("PN", "(no ping)"), ("PH", "@here"), ("PE", "@everyone")],
                default="PN",
                help_text="Options for pinging on notification",
                max_length=2,
            ),
        ),
    ]
