# Generated by Django 3.1.12 on 2021-07-09 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("structuretimers", "0002_auto_20210708_2151"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistancesFromStaging",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("light_years", models.FloatField(blank=True, default=None, null=True)),
                (
                    "jumps",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StagingSystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "eve_solar_system",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="+",
                        to="eveuniverse.evesolarsystem",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="timer",
            name="distance_from_staging",
        ),
        migrations.RemoveField(
            model_name="timer",
            name="jumps_from_staging",
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
        migrations.AddField(
            model_name="distancesfromstaging",
            name="staging_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distances",
                to="structuretimers.stagingsystem",
            ),
        ),
        migrations.AddField(
            model_name="distancesfromstaging",
            name="timer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distances",
                to="structuretimers.timer",
            ),
        ),
    ]
