# Generated by Django 3.2.10 on 2022-01-10 19:00

import multiselectfield.db.fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0002_distances_from_staging"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="exclude_timer_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("NO", "Unspecified"),
                    ("AR", "Armor"),
                    ("HL", "Hull"),
                    ("FI", "Final"),
                    ("AN", "Anchoring"),
                    ("UA", "Unanchoring"),
                    ("MM", "Moon Mining"),
                    ("TG", "Target"),
                ],
                help_text="Timer must NOT have one of the given timer types",
                max_length=23,
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="require_timer_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("NO", "Unspecified"),
                    ("AR", "Armor"),
                    ("HL", "Hull"),
                    ("FI", "Final"),
                    ("AN", "Anchoring"),
                    ("UA", "Unanchoring"),
                    ("MM", "Moon Mining"),
                    ("TG", "Target"),
                ],
                help_text="Timer must have one of the given timer types or leave blank to match any.",
                max_length=23,
            ),
        ),
        migrations.AlterField(
            model_name="timer",
            name="date",
            field=models.DateTimeField(
                db_index=True, help_text="Date when this timer happens", null=True
            ),
        ),
        migrations.AlterField(
            model_name="timer",
            name="timer_type",
            field=models.CharField(
                choices=[
                    ("NO", "Unspecified"),
                    ("AR", "Armor"),
                    ("HL", "Hull"),
                    ("FI", "Final"),
                    ("AN", "Anchoring"),
                    ("UA", "Unanchoring"),
                    ("MM", "Moon Mining"),
                    ("TG", "Target"),
                ],
                default="NO",
                max_length=2,
            ),
        ),
    ]
