# Generated by Django 2.2.13 on 2020-08-07 22:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0002_auto_20200807_2051"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationrule", name="exclude_important",
        ),
        migrations.RemoveField(model_name="notificationrule", name="exclude_opsec",),
        migrations.RemoveField(
            model_name="notificationrule", name="require_important",
        ),
        migrations.RemoveField(model_name="notificationrule", name="require_opsec",),
        migrations.AddField(
            model_name="notificationrule",
            name="is_important",
            field=models.CharField(
                choices=[("AN", "any"), ("RQ", "required"), ("EX", "excluded")],
                default="AN",
                help_text="Wether the timer must be important",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="notificationrule",
            name="is_opsec",
            field=models.CharField(
                choices=[("AN", "any"), ("RQ", "required"), ("EX", "excluded")],
                default="AN",
                help_text="Wether the timer must be OPSEC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="minutes",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "0"),
                    (5, "5"),
                    (10, "10"),
                    (15, "15"),
                    (30, "30"),
                    (45, "45"),
                    (60, "60"),
                    (90, "90"),
                    (120, "120"),
                ],
                db_index=True,
                help_text="Notifications are sent x minutes before timer elapses",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="require_visibility",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("UN", "unrestricted"),
                    ("AL", "Alliance only"),
                    ("CO", "Corporation only"),
                ],
                help_text="Visibility must be one of the selected or leave blank to match any.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="timer",
            name="location_details",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Additional information about the location of this structure, e.g. name of nearby planet / moon / gate",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="timer",
            name="objective",
            field=models.CharField(
                choices=[
                    ("UN", "undefined"),
                    ("HO", "hostile"),
                    ("FR", "friendly"),
                    ("NE", "neutral"),
                ],
                default="UN",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="timer",
            name="timer_type",
            field=models.CharField(
                choices=[
                    ("NO", "Unspecified"),
                    ("AR", "Armor"),
                    ("HL", "Hull"),
                    ("FI", "Final"),
                    ("AN", "Anchoring"),
                    ("UA", "Unanchoring"),
                    ("MM", "Moon Mining"),
                ],
                default="NO",
                max_length=2,
            ),
        ),
    ]
