# Generated by Django 3.2.10 on 2022-01-12 19:05

import multiselectfield.db.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0003_add_preliminary_timers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="exclude_timer_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("NO", "Unspecified"),
                    ("AR", "Armor"),
                    ("HL", "Hull"),
                    ("FI", "Final"),
                    ("AN", "Anchoring"),
                    ("UA", "Unanchoring"),
                    ("MM", "Moon Mining"),
                ],
                help_text="Timer must NOT have one of the given timer types",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="require_timer_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("NO", "Unspecified"),
                    ("AR", "Armor"),
                    ("HL", "Hull"),
                    ("FI", "Final"),
                    ("AN", "Anchoring"),
                    ("UA", "Unanchoring"),
                    ("MM", "Moon Mining"),
                ],
                help_text="Timer must have one of the given timer types or leave blank to match any.",
                max_length=20,
            ),
        ),
    ]
