# Generated by Django 3.2.10 on 2022-01-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0003_add_target_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="timer",
            name="last_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
