# Generated by Django 4.0.3 on 2022-04-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0004_add_space_type_and_region_filters"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationrule",
            old_name="exclude_region",
            new_name="exclude_regions",
        ),
        migrations.RenameField(
            model_name="notificationrule",
            old_name="exclude_space_type",
            new_name="exclude_space_types",
        ),
        migrations.RenameField(
            model_name="notificationrule",
            old_name="require_region",
            new_name="require_regions",
        ),
        migrations.RenameField(
            model_name="notificationrule",
            old_name="require_space_type",
            new_name="require_space_types",
        ),
    ]
