# Generated by Django 3.1.12 on 2021-07-09 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0005_auto_20210709_2241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulednotification",
            name="notification_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_notifications",
                to="structuretimers.notificationrule",
            ),
        ),
        migrations.AlterField(
            model_name="schedulednotification",
            name="timer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_notifications",
                to="structuretimers.timer",
            ),
        ),
    ]
