# Generated by Django 2.2.13 on 2020-08-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerboard2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='details',
        ),
        migrations.AddField(
            model_name='timer',
            name='structure_name',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
