# Generated by Django 2.2.13 on 2020-08-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="timer", name="scheduled_notifications",),
        migrations.AddField(
            model_name="timer",
            name="notification_rules",
            field=models.ManyToManyField(
                help_text="Notification rules conforming with this timer",
                through="timerboard2.ScheduledNotification",
                to="timerboard2.NotificationRule",
            ),
        ),
    ]
