# Generated by Django 2.2.13 on 2020-08-03 18:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0012_index_additions"),
        ("timerboard2", "0002_discordwebhook"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minutes",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[("0", "0"), ("5", "5"), ("5", "15"), ("5", "30")],
                        help_text="Time before event in minutes when notifications are sent",
                        max_length=7,
                    ),
                ),
                (
                    "require_timer_type",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("NO", "None"),
                            ("AR", "Armor"),
                            ("HL", "Hull"),
                            ("AN", "Anchoring"),
                            ("UA", "Unanchoring"),
                            ("MM", "Moon Mining"),
                        ],
                        help_text="Restrict to given timer types or leave blank to match any.",
                        max_length=17,
                    ),
                ),
                (
                    "objectives",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("UN", "Undefined"),
                            ("HO", "Hostile"),
                            ("FR", "Friendly"),
                            ("NE", "Neutral"),
                        ],
                        help_text="Restrict to given objectives or leave blank to match any.",
                        max_length=11,
                    ),
                ),
                (
                    "ping_type",
                    models.CharField(
                        choices=[
                            ("PN", "(no ping)"),
                            ("PH", "@here"),
                            ("PE", "@everybody"),
                        ],
                        default="PN",
                        help_text="Options for pinging for every notification",
                        max_length=2,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="whether this rule is currently active"
                    ),
                ),
                (
                    "alliances",
                    models.ManyToManyField(
                        help_text="Restrict to given alliances or leave blank to match any.",
                        to="eveonline.EveAllianceInfo",
                    ),
                ),
                (
                    "corporations",
                    models.ManyToManyField(
                        help_text="Restrict to given corporations or leave blank to match any.",
                        to="eveonline.EveCorporationInfo",
                    ),
                ),
                (
                    "webhooks",
                    models.ManyToManyField(
                        help_text="Webhooks notifications are sent to",
                        to="timerboard2.DiscordWebhook",
                    ),
                ),
            ],
        ),
    ]
