# Generated by Django 2.2.13 on 2020-08-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0002_auto_20200805_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulednotification",
            name="celery_task_id",
            field=models.CharField(default="", max_length=765),
        ),
    ]
