# Generated by Django 2.2.13 on 2020-08-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timerboard2', '0002_auto_20200801_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='eve_solar_system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.EveSolarSystem'),
        ),
    ]
