# Generated by Django 2.2.13 on 2020-08-03 19:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0004_auto_20200803_1859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="objectives",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("UN", "Undefined"),
                    ("HO", "Hostile"),
                    ("FR", "Friendly"),
                    ("NE", "Neutral"),
                ],
                default="",
                help_text="Restrict to given objectives or leave blank to match any.",
                max_length=11,
            ),
        ),
    ]
