# Generated by Django 2.2.13 on 2020-08-06 18:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timerboard2', '0004_auto_20200806_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='require_objectives',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('UN', 'undefined'), ('HO', 'hostile'), ('FR', 'friendly'), ('NE', 'neutral')], help_text='Timer must have one of the given objectives or leave blank to match any.', max_length=11),
        ),
        migrations.AlterField(
            model_name='timer',
            name='objective',
            field=models.CharField(choices=[('UN', 'undefined'), ('HO', 'hostile'), ('FR', 'friendly'), ('NE', 'neutral')], default='UN', max_length=2, verbose_name='objective'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='visibility',
            field=models.CharField(choices=[('UN', 'unrestricted'), ('AL', 'Alliance only'), ('CO', 'Corporation only')], db_index=True, default='UN', help_text='The visibility of this timer can be limited to members of your organization', max_length=2),
        ),
    ]
