# Generated by Django 2.2.13 on 2020-08-03 19:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0005_auto_20200803_1900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="alliances",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict to given alliances or leave blank to match any.",
                to="eveonline.EveAllianceInfo",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="corporations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict to given corporations or leave blank to match any.",
                to="eveonline.EveCorporationInfo",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="objectives",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("UN", "Undefined"),
                    ("HO", "Hostile"),
                    ("FR", "Friendly"),
                    ("NE", "Neutral"),
                ],
                help_text="Restrict to given objectives or leave blank to match any.",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="require_timer_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("NO", "None"),
                    ("AR", "Armor"),
                    ("HL", "Hull"),
                    ("AN", "Anchoring"),
                    ("UA", "Unanchoring"),
                    ("MM", "Moon Mining"),
                ],
                help_text="Restrict to given timer types or leave blank to match any.",
                max_length=17,
            ),
        ),
    ]
