# Generated by Django 2.2.13 on 2020-08-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0008_auto_20200803_1910"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discordwebhook", options={"ordering": ["name"]},
        ),
    ]
