# Generated by Django 2.2.13 on 2020-08-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0009_auto_20200803_1946"),
    ]

    operations = [
        migrations.AlterModelOptions(name="discordwebhook", options={},),
    ]
