# Generated by Django 2.2.13 on 2020-08-03 20:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0010_auto_20200803_1952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="minutes",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(0, "0"), (5, "5"), (15, "15"), (30, "30")],
                help_text="Time before event in minutes when notifications are sent",
                max_length=9,
            ),
        ),
    ]
