# Generated by Django 2.2.13 on 2020-08-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0011_auto_20200803_2001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="minutes",
            field=models.PositiveIntegerField(
                choices=[(0, "0"), (5, "5"), (15, "15"), (30, "30")],
                help_text="Time before event in minutes when notifications are sent",
            ),
        ),
        migrations.CreateModel(
            name="TimerNotificationProcessed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timerboard2.NotificationRule",
                    ),
                ),
                (
                    "timer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timerboard2.Timer",
                    ),
                ),
            ],
        ),
    ]
