# Generated by Django 2.2.13 on 2020-08-03 21:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0013_auto_20200803_2138"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timer", old_name="eve_corp", new_name="eve_corporation",
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="require_alliances",
            field=models.ManyToManyField(
                blank=True,
                help_text="Timer must be created by one of the given alliances or leave blank to match any.",
                to="eveonline.EveAllianceInfo",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="require_corporations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Timer must be created by one of the given corporations or leave blank to match any.",
                to="eveonline.EveCorporationInfo",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="require_objectives",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("UN", "Undefined"),
                    ("HO", "Hostile"),
                    ("FR", "Friendly"),
                    ("NE", "Neutral"),
                ],
                help_text="Timer must have one of the given objectives or leave blank to match any.",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="require_timer_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("NO", "None"),
                    ("AR", "Armor"),
                    ("HL", "Hull"),
                    ("AN", "Anchoring"),
                    ("UA", "Unanchoring"),
                    ("MM", "Moon Mining"),
                ],
                help_text="Timer must have one of the given timer types or leave blank to match any.",
                max_length=17,
            ),
        ),
    ]
