# Generated by Django 2.2.13 on 2020-08-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0014_auto_20200803_2151"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("timer_management", "Can create and edit timers"),
                ),
            },
        ),
    ]
