# Generated by Django 2.2.13 on 2020-08-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timerboard2", "0015_auto_20200804_2100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="minutes",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "0"),
                    (5, "5"),
                    (10, "10"),
                    (15, "15"),
                    (30, "30"),
                    (45, "45"),
                    (60, "60"),
                    (120, "120"),
                ],
                help_text="Time before event in minutes when notifications are sent",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="ping_type",
            field=models.CharField(
                choices=[("PN", "(no ping)"), ("PH", "@here"), ("PE", "@everyone")],
                default="PN",
                help_text="Options for pinging for every notification",
                max_length=2,
            ),
        ),
    ]
